# Check on http://lint.travis-ci.org/ after modifying it!
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install nose pep8 flake8 coverage coveralls
  - pip install .
script:
  - nosetests
  - pep8 burrito setup.py
  - flake8 burrito setup.py
  - coverage run setup.py test
  - coverage report -m
  - coveralls
