# Check on http://lint.travis-ci.org/ after modifying it!
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install nose pep8 flake8 coveralls
  - pip install .
script:
  - nosetests --with-coverage
  - pep8 burrito setup.py
  - flake8 burrito setup.py
after_success:
  - coveralls
